name: Update Deployment Time

on:
  push:
    branches:
      - master

jobs:
  update-deploy-time:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Update buildTime.js
        run: |
          current_time=$(TZ=America/Denver date +"%A, %B %d, %H:%M:%Z")
          echo "const lastCalcUpdate = '$(date -u)';" > buildTime.js

      - name: Commit changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "action@github.com"
          git add .
          git commit -m "Updated buildTime [skip ci]"
          git push